# Generated by Django 3.2.5 on 2023-03-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=None, verbose_name='房屋标题')),
                ('specs', models.CharField(max_length=64, null=None, verbose_name='房屋规格(几室几厅几卫)')),
                ('acreage', models.CharField(max_length=128, verbose_name='房屋大小')),
                ('price', models.CharField(max_length=128, verbose_name='房屋价格')),
                ('introduction', models.TextField(verbose_name='房屋简介')),
                ('house_img', models.ImageField(max_length=512, upload_to='house', verbose_name='房屋主图片')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.area', verbose_name='房屋地址')),
            ],
            options={
                'verbose_name': '房屋信息',
                'verbose_name_plural': '房屋信息',
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('id_card', models.CharField(max_length=32, verbose_name='身份证号')),
                ('license', models.ImageField(max_length=512, upload_to='license', verbose_name='营业执照')),
            ],
            options={
                'verbose_name': '卖家',
                'verbose_name_plural': '卖家',
                'db_table': 'seller_user',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=30, verbose_name='操作')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=512, upload_to='house', verbose_name='房屋具体图片')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.house', verbose_name='房屋信息')),
            ],
            options={
                'verbose_name': '房屋图片',
                'verbose_name_plural': '房屋图片',
                'db_table': 'house_image',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.user', verbose_name='房屋用户'),
        ),
    ]
