# Generated by Django 3.2.5 on 2023-03-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('id_card', models.CharField(max_length=32, verbose_name='身份证号')),
            ],
            options={
                'verbose_name': '买家',
                'verbose_name_plural': '买家',
                'db_table': 'buyer_user',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=30, verbose_name='操作')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['id'],
            },
        ),
    ]
